version: '3.9'
services:
  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: togeeat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d togeeat -U root" ]
      interval: 10s 
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DATABASE_URL: "postgresql://root:mysecret@postgres:5432/togeeat?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/sh -c "yarn --cwd /app prisma migrate deploy && node /app/dist/src/main.js"